Repository googleapis/nodejs-datacatalog, pull requests merged in 2020-06, with the labels that each got.

#167 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#168 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#172 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/data_catalog_client.ts
  src/v1beta1/data_catalog_client.ts
  src/v1beta1/policy_tag_manager_client.ts
  src/v1beta1/policy_tag_manager_serialization_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#174 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 fix: proper fallback option handling
  src/v1/data_catalog_client.ts
  src/v1beta1/data_catalog_client.ts
  src/v1beta1/policy_tag_manager_client.ts
  src/v1beta1/policy_tag_manager_serialization_client.ts
  synth.metadata
Labels: cla: yes, context: none

#177 feat: promote library to GA
  .repo-metadata.json
  README.md
  protos/google/cloud/datacatalog/v1/gcs_fileset_spec.proto
  protos/google/cloud/datacatalog/v1beta1/gcs_fileset_spec.proto
  synth.metadata
Labels: automerge, cla: yes

#178 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#179 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
