Repository googleapis/nodejs-datacatalog, pull requests merged in 2020-05, with the labels that each got.

#163 fix: regenerate unit tests
  synth.metadata
  test/gapic_data_catalog_v1.ts
  test/gapic_data_catalog_v1beta1.ts
  test/gapic_policy_tag_manager_serialization_v1beta1.ts
  test/gapic_policy_tag_manager_v1beta1.ts
Labels: automerge, cla: yes

#164 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#166 chore: enable gapicv2 for datacatalog/v1beta1 API
  protos/google/cloud/datacatalog/v1/datacatalog.proto
  protos/google/cloud/datacatalog/v1beta1/datacatalog.proto
  protos/protos.json
  src/v1/data_catalog_client.ts
  synth.metadata
Labels: cla: yes, context: full
