Repository googleapis/nodejs-datacatalog, pull requests merged in 2021-04, with the labels that each got.

#238 build: add missing compile-protos
  package.json
Labels: api: datacatalog, cla: yes

#243 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#247 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#248 chore: regenerate protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: api: datacatalog, cla: yes, context: none
